import Head from "next/head";

export default function Email() {
  return (
    <>
      <Head>
        <title>Chat-GPT Email Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <form className="flex flex-col items-center justify-center">
          <h1 className="text-4xl font-bold text-white">Chat-GPT Email Generator</h1>
          <p className="text-white">Generate emails from Chat-GPT!</p>
          <div className="flex flex-col items-center justify-center">
            <input
              className="w-96 h-10 px-5 py-3 mb-5 placeholder-gray-400 border rounded-lg focus:shadow-outline"
              placeholder="Email subject"
            />
            <input
              className="w-96 h-10 px-5 py-3 mb-5 placeholder-gray-400 border rounded-lg focus:shadow-outline"
              placeholder="Email to be addressed to"
            />
            <input
              className="w-96 h-10 px-5 py-3 mb-5 placeholder-gray-400 border rounded-lg focus:shadow-outline"
              placeholder="Email requirements"
            />
            <button className="w-96 h-10 px-5 py-3 mb-5 text-white bg-blue-500 rounded-lg hover:bg-blue-600">
              Generate
            </button>
          </div>
        </form>
      </main>
    </>
  );
}


