import Head from "next/head";
import { useState } from "react";
import { set, z } from "zod";
import { api } from "~/utils/api";

export default function Home() {
  const [email, setEmail] = useState("");
  
  return (
    <>
      <Head>
        <title>Chat-GPT Email Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <form className="flex flex-col items-center justify-center"
          onSubmit={(e) => {
            e.preventDefault();
            const formData = new FormData(e.currentTarget);
            const formResponse = 
              z.object({
                subject: z.string(),
                recipient: z.string(),
                requirements: z.string(),
              }).safeParse(Object.fromEntries(formData.entries()));

            if (!formResponse.success) {
              alert("Please fill out all fields!");
              return;
            }

            const res = api.email.generateEmail.useQuery(formResponse.data);

            if (res.error) {
              alert("An error occurred!");
              return;
            }

            setEmail(res.data ?? "Failed to generate email!");
          }}
        >
          <h1 className="text-4xl font-bold text-white">Chat-GPT Email Generator</h1>
          <p className="text-white">Generate emails from Chat-GPT!</p>
          <div className="flex flex-col items-center justify-center">
            <input
              className="w-96 h-10 px-5 py-3 mb-5 placeholder-gray-400 border rounded-lg focus:shadow-outline"
              placeholder="Email subject"
              name="subject"
            />
            <input
              className="w-96 h-10 px-5 py-3 mb-5 placeholder-gray-400 border rounded-lg focus:shadow-outline"
              placeholder="Email to be addressed to"
              name="recipient"
            />
            <input
              className="w-96 h-10 px-5 py-3 mb-5 placeholder-gray-400 border rounded-lg focus:shadow-outline"
              placeholder="Email requirements"
              name="requirements"
            />
            <button className="w-96 h-10 px-5 py-3 mb-5 text-white bg-blue-500 rounded-lg hover:bg-blue-600" type="submit">
              Generate
            </button>
          </div>
        </form>
        <div className="flex flex-col items-center justify-center">
          <h1 className="text-4xl font-bold text-white">Generated Email</h1>
          <p className="text-white">{email}</p>
        </div>
      </main>
    </>
  );
}
